### ISSUE TITLE
Grid data source not gracefully handling REST api that returns 404 when no items found

### ISSUE THREAD

**Issue by AlanBarber** [shieldui/shieldui-lite#10]
I have a REST api that when you call if it has no items to return a response code of 404 and an empty array.  The grid gets stuck with the loading spinner and throws an error in the console about the 404. 

How can I work around this to get it to accept the 404 and just render noRecordsText property?

**Comment by shieldui** [comment]
You can implement a remote.read handler function that invokes jQuery.ajax and in case of an error, calls the success handler with an empty array:

```
remote {
    read: function(params, success, error, extra) {
        $.ajax({
            ....
        }).then(success, $.proxy(success, null, []));
    }
}
```
