### ISSUE TITLE
Add custom event PDF

### ISSUE THREAD

**Issue by hackerunet** [shieldui/shieldui-lite#4]
Hello there, can you help out to add a custom event that just executes the passed function?
The pdf export functionality of this library is too standard, I want to use an external URL to process the resultant PDF sending my own parameters using $.ajax
So I added this to the main library but how can I make it just executes whatever I place inside the function??
thanks

`_pdfButtonClicked: function (e) {
            var self = this,
                args = self.trigger(COMMAND, {commandName: PDF, cancel:false });
                return;
        },`

**Comment by shieldui** [comment]
This particular version of Shield UI - shieldui-lite, does not contain any PDF functionality.

However, for your case, you can add a custom button, like a toolbar button (https://www.shieldui.com/documentation/grid/javascript/api/settings/toolbar/buttons) and in its click handler, take the data from the grid's dataSource property and pass it to an external PDF creation service.
